export const FETCH_PROPERTIES = "FETCH_PROPERTIES";
export const ORDER_PROPERTIES = "ORDER_PROPERTIES";
export const FILTER_PROPERTIES = "FILTER_PROPERTIES";
export const LOAD_COUNTRIES = "LOAD_COUNTRIES";
export const ADMIN_SESSION = "ADMIN_SESSION";
